# Generated by Django 5.1.7 on 2025-03-13 16:46

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10),
        ),
    ]
