# Generated by Django 5.1.7 on 2025-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remote_timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
