# Generated by Django 5.1.7 on 2025-04-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_transaction_remote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
